/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119072-g5fac8d062d-20250329"
#endif /* AVUTIL_FFVERSION_H */
